source 'https://rubygems.org'

# ruby '2.6.1'

gem 'sinatra', '~> 2.2'
gem 'sinatra-contrib', '~> 2.0', '>= 2.0.8.1'
gem 'erubis', '~> 2.7'
gem 'minitest'
gem 'rack-test'
gem 'redcarpet'
gem 'fileutils'
gem 'bcrypt'

gem "pry-remote"
gem "pry"